apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-demo
  labels:
    app: docker-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-demo
  template:
    metadata:
      labels:
        app: docker-demo
    spec:
      containers:
        - name: search
          image: https://hub.docker.com/repository/docker/gnair123/demo_repo123:v1
          ports:
            - containerPort: 80
              name: http
          imagePullPolicy: Always
