apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-demo
  namespace: default
  labels:
    app: docker-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-demo
  template:
    metadata:
      labels:
        app: docker-demo
    spec:
      containers:
        - name: docker-demo
          image: gnair123/demo_repo123:#{Build.BuildId}#
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
      imagePullSecrets:
        - name: doc-kub-sec
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: docker-demo
