apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-demo
  labels:
    app: docker-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-demo
  template:
    metadata:
      labels:
        app: docker-demo
    spec:
      containers:
        - name: docker-demo
          image: gnair123/demo_repo123:#{Build.BuildId}#
          ports:
            - containerPort: 80
              name: http
      imagePullSecrets:
        - name: doc-kub-sec
        
kind: Service 
apiVersion: v1 
metadata:
  name: docker-demo-service 
spec:
  type: LoadBalancer
  selector:
    app: docker-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
